### ISSUE TITLE
Config Page has to be saved twice

### ISSUE THREAD

**Issue by patrickhener** [SmartVisuTNG/smartvisu#29] opened 2016-08-24 09:57 UTC
Recalling an old faulty behaviour of the smartVISU I have to save the config page twice to get it to save the changes. For example when changing the theme I save. The it reloads the config page with the old settings. I then choose the new theme again and save. In the second run the changes are saved.

**Comment by i-am-offline** [comment] 2016-08-24 10:10
Duplicate of #22

**Closed by i-am-offline** 2016-08-24 10:10 UTC

**Comment by patrickhener** [comment] 2016-08-24 10:20
sorry

**Comment by i-am-offline** [comment] 2016-08-24 10:25
No Problem ... Just to keep the number of issues low 😉
